### ISSUE TITLE
Identity Platform examples

### ISSUE THREAD

**Issue by koesper** [terraform-google-modules/docs-examples#5]
Where are the examples for Identity Platform?
According to the "open in cloudshell" button in a few of the Terraform Modules, there should be a folder called `identity_platform_oauth_idp_config_basic`.
(When you press the "open in cloudshell" button, it opens a shell that tries to do something in that folder).

This link is in the documentation for the following modules:
- https://www.terraform.io/docs/providers/google/r/identity_platform_oauth_idp_config.html
- https://www.terraform.io/docs/providers/google/r/identity_platform_tenant_default_supported_idp_config.html
- https://www.terraform.io/docs/providers/google/r/identity_platform_tenant_inbound_saml_config.html
- https://www.terraform.io/docs/providers/google/r/identity_platform_tenant_oauth_idp_config.html

Either the "open in cloud shell" buttons havent been tested, or the folder has been removed.

In any case, some more documentation about Identity Platform would be appreciated!

**Comment by danawillow** [comment]
@rileykarson is syncing the examples over here a manual process?

**Comment by rileykarson** [comment]
Yep, it's currently manual. I've been waiting for the Magician v2 to automate it, since any work on Magician v1 would be throw-away.

@koesper: Sorry about those examples getting missed! They're added now, I'd missed syncing this repo for a couple releases.
