### ISSUE TITLE
google_firebase_project example does not exist in repo, breaks open in cloud shell button in html docs

### ISSUE THREAD

**Issue by ncouture** [terraform-google-modules/docs-examples#85]
The google_firebase_project documentation links to an inexisting example.

This causes the "Open in Google Cloud Shell" button to malfunction as target code is not found in repository `docs-examples`.

 - https://www.terraform.io/docs/providers/google/r/firebase_project.html#example-usage-firebase-project-basic
 - https://console.cloud.google.com/cloudshell/open?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fterraform-google-modules%2Fdocs-examples.git&cloudshell_working_dir=firebase_project_basic&cloudshell_image=gcr.io%2Fgraphite-cloud-shell-images%2Fterraform%3Alatest&open_in_editor=main.tf&cloudshell_print=.%2Fmotd&cloudshell_tutorial=.%2Ftutorial.md

```
$ cloudshell_open --repo_url "https://github.com/terraform-google-modules/docs-examples.git" --print_file "./motd" --dir "firebase_project_basic" --page "editor" --tutorial "./tutorial.md" --open_in_editor "main.tf"
2020/09/12 05:25:02 Cloning https://github.com/terraform-google-modules/docs-examples.git into /home/nicolas_couture/cloudshell_open/docs-examples
Cloning into '/home/nicolas_couture/cloudshell_open/docs-examples'...
remote: Enumerating objects: 1309, done.
remote: Total 1309 (delta 0), reused 0 (delta 0), pack-reused 1309
Receiving objects: 100% (1309/1309), 281.37 KiB | 3.43 MiB/s, done.
Resolving deltas: 100% (996/996), done.
Path /home/nicolas_couture/cloudshell_open/docs-examples/firebase_project_basic/main.tf does not exist
Tutorial file /home/nicolas_couture/cloudshell_open/docs-examples/firebase_project_basic/tutorial.md does not exist or is not a file
-bash: cd: /home/nicolas_couture/cloudshell_open/docs-examples/firebase_project_basic: No such file or directory
```

**Comment by yuryninog** [comment]
Hi @ncouture:

I think this issue expired ... I was not able to find the project firebase_project_basic in this repository. Could you confirm please if the issue persist? please ...
